---
title: "MSc Project"
author: "SOBOYEJO LUKMAN ADEBOYE"
date: "01/06/2020"
output: html
always_allow_html: true
---

```{r global_options, include = FALSE}
knitr::opts_knit$set(echo= FALSE)
```


## Packages Installed ----------------------------------------------------------------------------
```{r}

(c("forecast", "patchwork", "ggplot2", "plotly", "tidyverse", "pander", "ggthemes", "reshape", "cowplot", "patchwork"))
# install.packages(pkgs)

library(forecast)   # For the moving avearage timeseries
library(patchwork)  # For combining plots
library(ggplot2)    # For Visualization
library(plotly)     # For interactive plot
library(lubridate)  #
library(knitr)
library(tidyverse)
library(pander)
library(ggthemes)
library(reshape2)
library(cowplot)

```



## Read file into R -----------------------------------------------------------------------
# Monthly Time series

```{r}

san.mon.data <- read.csv("D:/Bologna Project/Land_Reclamation_Excel_Data/Sanvitale.R/SanVitale Basin/san.mon.csv")
ras.mon.data <- read.csv("D:/Bologna Project/Land_Reclamation_Excel_Data/Rasponi.R/Rasponi Basin/ras.mon.csv")
quin.mon.data <- read.csv("D:/Bologna Project/Land_Reclamation_Excel_Data/Fosso_Ghiaia.R/Quinto Basin/quin.mon.csv")


# Yearly Time series

quin.ann.data <- read.csv("D:/Bologna Project/Land_Reclamation_Excel_Data/Fosso_Ghiaia.R/Quinto Basin/quin.ann.csv")
ras.ann.data <- read.csv("D:/Bologna Project/Land_Reclamation_Excel_Data/Rasponi.R/Rasponi Basin/ras.ann.csv")
san.ann.data <- read.csv("D:/Bologna Project/Land_Reclamation_Excel_Data/Sanvitale.R/SanVitale Basin/san.ann.csv")

# kable()
# pander()

```


## Monthly Precipitation ------------------------------------------------------------------------
```{r}
## Date Conversion to POSXCIT
newyear = parse_date_time(san.mon.data[, 1], "by")
date = as.Date.POSIXct(newyear)


# Time Series of precipitation
rain.ts <- ts(san.mon.data$p,
              frequency = 12,
              start = c(1971, 1))

# moving average
rain.ma = ma(rain.ts, order = 12, centre = T)
# unclass rain moving average
unclass.rain <- unclass(rain.ma)


# combined different type of object
df.rain <- data.frame(date, unclass.rain)

# Data Visualization - ggplot2
(
  ppt = ggplot(df.rain,
               aes(x = date, y = unclass.rain)) +
    geom_line() +
    geom_smooth(
      method = "loess",
      formula = y ~ x,
      span = 0.3,
      level = 0.95,
      se = FALSE,
      na.rm = TRUE
    ) +
    labs(
      caption = "Data Source: ARPAe Emilia Romagna",
      title = "Monthly Rainfall",
      subtitle = "Rainfall (mm/month) representing the three coastal basins",
      y = "P (mm/month)",
      x = "Time",
      tag = "a"
    ) +
    scale_x_date(date_breaks = "5 year",
                 date_labels = "%Y") +
    theme_cowplot() 
  # annotate(
  #   geom = "curve",
  #   x = as.Date("2000-04-01"),
  #   y = 95,
  #   xend = as.Date("1998-04-01"),
  #   yend = 80,
  #   curvature = 0.5,
  #   arrow = arrow(length = unit(2, "mm"))
  # ) +
  # annotate(
  #   geom = "text",
  #   x = as.Date("2001-04-01"),
  #   y = 95,
  #   label = "maximum rainfall",
  #   hjust = "left",
  #   size = 5
  # ) +
  # annotate(
  #   geom = "curve",
  #   x = as.Date("1993-04-01"),
  #   y = 30,
  #   xend = as.Date("1988-04-01"),
  #   yend = 35,
  #   curvature = -0.3,
  #   arrow = arrow(length = unit(2, "mm"))
  # ) +
  # annotate(
  #   geom = "text",
  #   x = as.Date("1994-04-01"),
  #   y = 35,
  #   label = "mininmum rainfall",
  #   hjust = "left",
  #   size = 5
  # )
)


# ggsave(filename = "ppt.png",
#        dpi = 1200, height = 4,
#        width = 10,
#        path = "D:/Bologna Project/Land_Reclamation_Excel_Data/Project_Manuscript/Presentation")
# dev.off()

```

